### PR TITLE
Add multiarch docker options

### PR DESCRIPTION
**Pull request by meyskens**
This adds the option to specify the architecture which to use in the Docker build. This allows for the plugin to be used on multiple platforms.
For release this should use a Manifest (https://github.com/estesp/manifest-tool, hopefully soon inside Docker itself) but I was unable to find where this is being built.

Feedback welcome!

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks for the PR @meyskens - Sorry to inform you we will be deprecating this project. We will still accept this PR though.

**Comment by harshavardhana** [comment]
@meyskens looks like there are conflicts now from recent merge. can you update the PR?

**Comment by meyskens** [comment]
@harshavardhana sad to see this being deprecated :( Any alternatives you can suggest?
On a less sad note: I've fixed the conflict.

**Comment by harshavardhana** [comment]
> @harshavardhana sad to see this being deprecated :( Any alternatives you can suggest?
> On a less sad note: I've fixed the conflict.

@meyskens yes the alternative is `rexray/s3fs` https://github.com/codedellemc/rexray - still the following PR is needed https://github.com/codedellemc/rexray/pull/1042 for it to work. 

We will deprecate MinFS once we have rexray documented.  Thanks for rebasing the PR.

**Pull request merged**
